image: git.pushok.com:4567/pushok/tinelic/tinelic-test

cache:
  key: "$CI_PIPELINE_ID"
  paths:
  - node_modules/
  - modules/web/app/

stages:
  - build
  - test

build:
  stage: build
  variables:
    NODE_ENV: "development"
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - npm i
    - npm i --no-save grunt-cli
  script:
    - ./node_modules/.bin/grunt build

test:
  stage: test
  variables:
    NODE_ENV: "test"
  services:
    - mongo:3.4
  script:
    - npm test
  retry: 2
